#
# 'docker-compose up'
#

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker-php.dockerfile
      args:
        - APACHE_RUN_USER=${COMPOSE_APACHE_RUN_USER}
        - APACHE_RUN_GROUP=${COMPOSE_APACHE_RUN_GROUP}
    restart: "no"
    volumes:
      - ".:/var/www/html"
      - "./docker-data/log:/var/log/apache2"
      - "./docker-data/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    ports:
      - ${COMPOSE_WEB_PORT}

      # imposta l'hostname (come ritornato da gethostname()) INTERNAMENTE AL CONTAINER. Non ha effetto all'esterno
    hostname: ${COMPOSE_PROJECT_NAME}.localhost
    # utente default di esecuzione dei comandi nel container, utilizza utente del sistema host (es. bash)
    user : ${COMPOSE_APACHE_RUN_USER}
  db:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE : ${DB_DATABASE}
      MYSQL_USER : ${DB_USERNAME}
      MYSQL_PASSWORD : ${DB_PASSWORD}
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - ${COMPOSE_MYSQL_PORT} 
  composer_install:
    image : composer:2
    command: ["composer", "install"]
    volumes:
      - "./:/app"
  # raggiungibile su {hostname}:5000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: "no"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT : 200000000
    ports:
      - ${COMPOSE_PHPMYADMIN_PORT}
  node:
    image : node:12
    command: >
      sh -c "npm install --save-dev && npm run watch"
    volumes:
      - "./:/app"
    working_dir: /app
    ports:
      - ${MIX_BROWSERSYNC_PORT}:${MIX_BROWSERSYNC_PORT}
